.TH CHAPSD 8 2014-09-16 "Linux" "Linux Programmer's Manual"
.SH NAME
chapsd \- Chaps PKCS#11 service daemon
.SH DESCRIPTION
Chapsd is a daemon that provides core functionality for the Chaps implementation of the PKCS#11 API.
.SH OPTIONS
.TP
.B \-\-auto_load_system_token
Automatically load a system wide PKCS#11 token.
.TP
.B \-\-srk_password PASSWORD
Use PASSWORD as the password for the TPM's storage root key (SRK).
.TP
.B \-\-srk_zeroes COUNT
Use a sequence of COUNT zeroes as the password for the TPM's storage root key (SRK).
.SH SEE ALSO
.BR chaps_client (8)
